#!/usr/bin/env bash
##? XXX_SCRIPT_DESCRIPTION_XXX
##?
##?
##? Usage:
##?   XXX_SCRIPT_NAME_XXX [-h | --help]
##?   XXX_SCRIPT_NAME_XXX [-v | --version]
##?
##? Options:
##?   -h --help     Show this help
##?   -v --version  Show the program version
##?
##? Author:
##?   XXX_SCRIPT_AUTHOR_XXX <XXX_SCRIPT_AUTHOR_EMAIL_XXX>
##?
#? v1.0.0

case ${1:-} in
  # Any subcommand should be here
  *)
    output::error "Exit with error: no content yet"
    exit 1
    ;;
esac
