#!/usr/bin/env bash
#shellcheck disable=SC2016

set -euo pipefail

##### Start of Homebrew Installation Patch #####
# export HOMEBREW_SLOTH=true
# export SLOTH_PATH="HOMEBREW_PREFIX/opt/dot"
##### End of Hombrew Installation Patch #####

if [[ -z "${SLOTH_PATH:-}" ]]; then
  SLOTH_PATH="${SLOTH_PATH:-${DOTLY_PATH:-${BASH_SOURCE[0]//\/scripts\/core\/install/}}}"
fi

#shellcheck disable=SC1091
. "${SLOTH_PATH:-}/scripts/core/src/_main.sh"
dot::load_library "install.sh"

start_sudo() {
  [[ "${DOTLY_ENV:-PROD}" == "CI" ]] && return
  if ! has_sudo; then
    command -p sudo -v -B
    if has_sudo && [[ -z "${SUDO_PID:-}" ]]; then
      (while true; do
        command -p sudo -v
        command -p sleep 30
      done) &
      SUDO_PID="$!"
      builtin trap stop_sudo SIGINT SIGTERM
    fi
  fi
}

stop_sudo() {
  builtin kill "$SUDO_PID" > /dev/null 2>&1
  builtin trap - SIGINT SIGTERM
  command -p sudo -k
}

has_sudo() {
  [[ "${DOTLY_ENV:-PROD}" == "CI" ]] && return
  command -p sudo -n -v > /dev/null 2>&1
}

initilize_sloth_if_necessary() {
  if ! git::is_in_repo -C "${SLOTH_PATH:-}" > /dev/null 2>&1; then
    output::answer "Initilizing .Sloth as repository"
    sloth_update::sloth_repository_set_ready 2>&1 | log::file "Initilizing .Sloth as repository" || true
    output::empty_line
  else
    output::answer ".Sloth is already a repository"
  fi

  output::answer "Updating .Sloth submodules"
  git::git -C "${SLOTH_PATH:-}" submodule update --init --recursive 2>&1 | log::file "Update .Sloth submodules" || true
  output::empty_line
}

##? Install dotly and setup dotfiles. By default use a interactive backup (backups are not done for core symlinks).
##?
##? Usage:
##?    install [-v | --version]
##?    install [-h | --help]
##?    install [[-n | --never-backup] | [-b |--always-backup] | [--ignore-symlinks]] [--ignore-loader] [--ignore-restoration] [--only-git-init-sloth] [--link_prefix <prefix>]
##?
##? Options:
##?    -h --help                Prints this help
##?    -n --never-backup        Never do a backup of user symlinks without prompt
##?    -b --always-backup       Always do a backup of user symlinks without prompt
##?    -i --interactive-backup  Interactive backup of user symlinks asking for
##?                             every existing symlink before to be applied (default).
##?    --ignore-symlinks        Ignore apply symlinks. Useful for very custom
##?                             installations.
##?    --ignore-loader          Ignore the modification of .bashrc, .zshrc and .zshenv
##?                             (see \`dot core loader --help\` for non default
##?                             locations of these files)
##?    --ignore-restoration     Ignore user restoration scripts
##?    --only-git-init-sloth    Executes only the .Sloth initilization if necessary
##?    --ignore-link            Does not install \`dot\` for all users in /usr/local/bin
##?                             This option is applied always if .Sloth was installed
##?                             with Brew Package Manager.
##?    --link-prefix            Link prefix for where to link the \`dot\` it will be \`${LINK_PREFIX}/bin\`
##?
#? v3.2.0
if ! ${DOTLY_INSTALLER:-false} && package::is_installed "docopts" || [[ "${1:-}" == "-h" || "${1:-}" == "--help" || "${1:-}" == "-v" || "${1:-}" == "--version" ]]; then
  docs::parse "$@"
  link_prefix="${prefix:-/usr/local}"
else
  backup=false
  interactive_backup=false
  ignore_backup=false
  ignore_symlinks=false
  ignore_loader=false
  ignore_restoration=false
  only_git_init_sloth=false
  ignore_link=false
  link_prefix=/usr/local
  while [[ $# -gt 0 ]]; do
    case "${1:-}" in
      --backup)
        { $interactive_backup || $ignore_backup; } && output::error "Error you can not use \`--backup\` with \`--interactive-backup\` or \`--ignore-backup\`" && exit 4
        backup=true
        ;;
      --interactive-backup)
        { $backup || $ignore_backup; } && output::error "Error you can not use \`--interactive-backup\` with \`--backup\` or \`--ignore-backup\`" && exit 4
        interactive_backup=true
        shift
        ;;
      --ignore-backup)
        { $backup || $interactive_backup; } && output::error "Error you can not use \`--ignore-backup\` with \`--backup\` or \`--interactive-backup\`" && exit 4
        ignore_backup=true
        shift
        ;;
      --ignore-symlinks)
        ignore_symlinks=true
        shift
        ;;
      --ignore-loader)
        ignore_loader=true
        shift
        ;;
      --ignore-restoration)
        ignore_restoration=true
        shift
        ;;
      --only-git-init-sloth)
        only_git_init_sloth=true
        shift
        ;;
      --ignore-link)
        ignore_link=true
        shift
        ;;
      --link-prefix)
        [[ -z "${2:-}" ]] && output::error "Wrong usage of \`--link-prefix\` option, it should include a second param with the prefix where to link \`dot\` command." && exit 4
        link_prefix="${2:-}"
        shift 2
        ;;
      *)
        break 2
        ;;
    esac
  done
fi

if ${only_git_init_sloth:-false}; then
  if platform::command_exists brew && ! brew list gtrabanco/tools/dot > /dev/null 2>&1; then
    initilize_sloth_if_necessary
  else
    output::answer "Skiping init .Sloth installation as repository because you have used a package manager to install it"
  fi
  exit
fi

# Default values in CI env
if [[ "${DOTLY_ENV:-PROD}" == "CI" ]]; then
  export SETUP_ZSH_AND_BASH_IN_SHELLS=false
  export IGNORE_APPLY_SYMLINKS=false
  export SYMLINKS_ARGS=(--ignore-backup)
  export SETUP_ZSH_AS_DEFAULT_SHELL=false
  export DOTFILES_PATH="${HOME}/.dotfiles"
  ignore_loader=true
  ignore_restoration=true
  IGNORE_UPDATE_PACKAGES=true
  DOTFILES_PATH="${HOME}/.dotfiles"
fi

#### Prompt user all the staff we want to know ####
#### All questions at the very beginning
# Adds zsh and bash in /etc/shells (only in macos, in linux is done by the package manager)
if
  platform::is_macos &&
    [[ -z "${SETUP_ZSH_AND_BASH_IN_SHELLS:-}" ]]
then
  SETUP_ZSH_AND_BASH_IN_SHELLS=false
  if
    output::yesno "Do you want to setup more modern \`zsh\` & \`bash\` as valid shells in \`/etc/shells\` (elevation required; sudo)"
  then
    start_sudo

    has_sudo && SETUP_ZSH_AND_BASH_IN_SHELLS=true
    ! has_sudo && output::error "It can not be done without elevation, aborting this options (should be done later manually)" && SETUP_ZSH_AND_BASH_IN_SHELLS=false
  fi

# If defined the variable, we need to cache the sudo password
elif
  platform::is_macos &&
    ${SETUP_ZSH_AND_BASH_IN_SHELLS:-false}
then
  start_sudo

  ! has_sudo &&
    output::error "It can not be done without elevation, aborting this options (should be done later manually)" &&
    SETUP_ZSH_AND_BASH_IN_SHELLS=false
fi
export SETUP_ZSH_AND_BASH_IN_SHELLS

# Backups
if
  ! ${IGNORE_APPLY_SYMLINKS:-false} &&
    [[ -z "${SYMLINKS_ARGS[*]:-}" ]]
then
  SYMLINKS_ARGS=(--interactive-backup)
  if ${never_backup:-}; then
    SYMLINKS_ARGS=(--ignore-backup)
  elif ${always_backup:-}; then
    SYMLINKS_ARGS=(--backup)
  else
    bk=false
    output::yesno "Do you want to perform a backup of symlinks before apply them (this will include all existing files)" && bk=true
    $bk && output::yesno "Do you want to be asked for every file" || SYMLINKS_ARGS=(--backup)
    ! $bk && SYMLINKS_ARGS=(--ignore-backup)
  fi
fi
export SYMLINKS_ARGS

# ZSH as default Shell
zsh_shell_path="$(command -v zsh || true)"
if [[ -z "${SETUP_ZSH_AS_DEFAULT_SHELL:-}" ]]; then
  SETUP_ZSH_AS_DEFAULT_SHELL=false
  if
    [[ "$SHELL" == *"zsh"* ]] &&
      platform::command_exists chsh &&
      [[ -x "$zsh_shell_path" ]] &&
      [[ -f "/etc/shells" ]] &&
      ! grep -q "^${zsh_shell_path}$" "/etc/shells"
  then
    output::yesno "Do you want to setup the zsh \`$zsh_shell_path\` as default shell" &&
      SETUP_ZSH_AS_DEFAULT_SHELL=true

    output::answer "This will need a sudo authentication to add it to \`/etc/shells\` file"
    start_sudo
    if ! has_sudo; then
      output::error "Without sudo authentication this can not be done. You should do this later manually"
      SETUP_ZSH_AS_DEFAULT_SHELL=false
    fi
  fi
elif
  ${SETUP_ZSH_AS_DEFAULT_SHELL:-false} &&
    [[ "$SHELL" == *"zsh"* ]] &&
    platform::command_exists chsh &&
    [[ -x "$zsh_shell_path" ]] &&
    [[ -f "/etc/shells" ]] &&
    ! grep -q "^${zsh_shell_path}$" "/etc/shells"
then
  start_sudo
  ! has_sudo &&
    output::error "\`SETUP_ZSH_AS_DEFAULT_SHELL\` should be aborted because sudo elevation password is not set." &&
    SETUP_ZSH_AS_DEFAULT_SHELL=false
else
  SETUP_ZSH_AS_DEFAULT_SHELL=${SETUP_ZSH_AS_DEFAULT_SHELL:-false}
fi
export SETUP_ZSH_AS_DEFAULT_SHELL
#### End of prompt user all the staff we want to know ####

export ZIM_HOME="${DOTFILES_PATH:-}/shell/zsh/.zimfw"
export PATH="$HOME/.cargo/bin:$PATH"

if platform::command_exists brew && ! brew list gtrabanco/tools/dot > /dev/null 2>&1; then
  # Initilize .Sloth only if necessary
  initilize_sloth_if_necessary
fi

# OS specific packages
output::answer "Installing specific OS packages if not installed"
if platform::is_macos; then
  output::answer "🍎 Setting up macOS platform"
  install_macos_custom
elif platform::is_linux; then
  output::answer "🐧 Setting up Linux Platform"
  install_linux_custom
fi
output::empty_line

# Packages that are necessary but not in CI env
if [[ "${DOTLY_ENV:-PROD}" != "CI" ]]; then
  script::depends_on docopts fzf yq cargo-update
fi

if [[ -n "$DOTFILES_PATH" ]]; then
  output::answer "Creating dotfiles structure"
  "${SLOTH_PATH:-}/bin/dot" dotfiles create "$DOTFILES_PATH" | log::file "Creating dotfiles structure" || exit 1
  output::empty_line
else
  output::answer "Skipping dotfiles creation"
  output::write "If you want to do it later, execute:"
  output::answer "\`dot dotfiles create\`"
fi

# Apply user symlinks
if ! ${ignore_symlinks:-false} && ! ${IGNORE_APPLY_SYMLINKS:-false}; then
  output::answer "Setting up symlinks"
  SYMLINKS_ARGS=(--interactive-backup)
  if [[ -z "${DOTFILES_PATH:-}" ]]; then
    if "${SLOTH_PATH:-}/bin/dot" symlinks apply "${SYMLINKS_ARGS[@]}" --continue-on-error --after-core 2>&1 | log::file "Applying symlinks"; then
      output::solution "Symlinks applied"
    else
      output::error "All symlinks were applied with errors. Use \`dot self debug\` to see what's wrong"
    fi
  else
    if "${SLOTH_PATH:-}/bin/dot" symlinks apply "${SYMLINKS_ARGS[@]}" --continue-on-error core 2>&1 | log::file "Applying symlinks"; then
      output::solution "Symlinks applied"
    else
      output::error "All symlinks were applied with errors. Use \`dot self debug\` to see what's wrong"
    fi
  fi

  if [[ ! -L "${HOME}/.bashrc" ]]; then
    output::error "Failed to symlink .bashrc"
  fi

  if [[ ! -L "${HOME}/.bash_profile" ]]; then
    output::error "Failed to symlink .bash_profile"
  fi

  if [[ ! -L "${HOME}/.zshrc" ]]; then
    output::error "Failed to symlink .zshrc"
  fi

  if [[ ! -L "${HOME}/.zshenv" ]]; then
    output::error "Failed to symlink .zshenv"
  fi

  if [[ ! -L "${HOME}/.zimrc" ]]; then
    output::error "Failed to symlink .zimrc"
  fi

  if [[ ! -L "${HOME}/.zlogin" ]]; then
    output::error "Failed to symlink .zlogin"
  fi

  output::empty_line
else
  output::answer "Skipping the symlinks apply"
fi
touch "$HOME/.z"
unset SYMLINKS_ARGS bk

if ! ${ignore_loader}; then
  # Adding .Sloth loader to bashrc and zshrc
  output::answer "Adding .Sloth loader to .bashrc and .zshrc"
  "${SLOTH_PATH:-}/bin/dot" core loader --modify
fi

# ZSH as default shell if we are using zsh
zsh_shell_path="$(command -v zsh || true)"
output::answer "Trying to setup zsh as the default shell"
if $SETUP_ZSH_AS_DEFAULT_SHELL && has_sudo; then
  sudo bash -c "echo '$zsh_shell_path' | tee -a /etc/shells" > /dev/null 2>&1

  {
    sudo chsh -s "$(command -v zsh)" 2>&1 || output::write "Shell could not be changed to zsh"
  } | log::file "Setting zsh as default shell"

elif [[ "${DOTLY_ENV:-PROD}" != "CI" ]]; then
  output::answer "ZSH is not installed or you decide not to setup as default shell."
else
  output::answer "This is step is aborted on CI"
fi
output::empty_line
unset zsh_shell_path

# If exists zsh install ZIMFW
output::answer "Installing zim"
if platform::command_exists zsh; then
  registry::install zimfw
else
  output::answer "ZIM Framework not installed because zsh shell were not found"
  output::write "Use \`dot self debug\` to view what happened"
  output::write "You will need to run manually the ZIM Framework install command"
  output::write "  zsh \`$ZIM_HOME/zimfw.zsh\` install"
fi
output::empty_line

if [[ "${DOTLY_ENV:-PROD}" != "CI" ]] && platform::command_exists zsh; then
  output::answer "Installing completions"

  {
    zsh "${SLOTH_PATH:-}/bin/dot" shell zsh reload_completions > /dev/null 2>&1 &&
      output::solution '✅ ZSH Completions realoaded'
  } || output::error '❌ Error reloading completions. Execute later \`dot shell zsh reload_completions\`'

  output::empty_line
fi

if
  platform::command_exists brew && ! brew list gtrabanco/tools/dot > /dev/null 2>&1 ||
    ! ${ignore_link:-false}
then
  output::answer "Linking dot command for all users in \`${link_prefix}/bin\`"
  ln -f -s "${SLOTH_PATH:-}/bin/dot" "${link_prefix}/bin/dot"
  [[ -x "${link_prefix}/dot" ]] || output::error "\`dot\` command could not be linked"
  output::empty_line
fi

if ! ${ignore_restoration:-false} && ! ${IGNORE_RESTORATION:-false}; then
  output::answer "Executing custom restoration scripts"
  install_scripts_path="${DOTFILES_PATH}/restoration_scripts"
  if [ -d "$install_scripts_path" ]; then
    find "$install_scripts_path" -mindepth 1 -maxdepth 1 -type l,f -name '*.sh' |
      sort |
      while read -r install_script; do
        #shellcheck disable=SC1090
        {
          [[ -x "$install_script" ]] && . "$install_script" | log::file "Executing afterinstall: $(basename "$install_script")"
        } || {
          output::error "Install script error in \`$(basename "$install_script")\`"
        }
      done
  fi
fi

output::empty_line
output::answer '🥳 🎉 .Sloth installed sucessfully'
output::empty_line

output::answer "Trying to load .Sloth"
if [[ -r "${SLOTH_PATH:-}/shell/init-sloth.sh" ]]; then
  output::solution "Loading .Sloth"
  #shellcheck disable=SC1091
  source "${SLOTH_PATH:-}/shell/init-sloth.sh" | log::file ".Sloth initiliser" || output::error "Error while loading .Sloth"

  if [[ "${DOTLY_ENV:-PROD}" == "CI" ]]; then
    echo "$PATH" | tr ':' '\n' | log::file ".Sloth PATH's for Debugging"

    if echo "$PATH" | grep -q "^${SLOTH_PATH:-}/bin:"; then
      output::error "You need to add ${SLOTH_PATH:-}/bin to your PATH at the first place"
      output::answer "\`export PATH=\"${SLOTH_PATH:-}/bin:$PATH\"\`"
      exit 1
    fi
  fi
else
  output::error ".Sloth could not be initilised"
  exit 1
fi
output::empty_line

if ! ${IGNORE_UPDATE_PACKAGES:-false}; then
  output::answer "Updating all system packages"
  if platform::is_macos; then
    output::empty_line
    output::write "IMPORTANT!!!"
    output::empty_line
    output::write "If you see any error updating openssl gem execute:"
    output::answer "\`dot mac fix_gem_openssl\`"
    output::answer "More info: https://www.gitmemory.com/issue/ruby/openssl/385/656744433"
    output::empty_line
  fi
  "${SLOTH_PATH:-}/bin/dot" package update_all | log::file "Updating all system packages"
  output::empty_line
elif ${IGNORE_UPDATE_PACKAGES:-false}; then
  output::answer "All system packages update aborted by the user"
fi

output::solution "🏁 Now restart your terminal to finish the installation"
