#!/usr/bin/env bash

set -euo pipefail

[[ -z "${SLOTH_PATH:-}" ]] && exit 1

#shellcheck disable=SC1091
. "${SLOTH_PATH:-}/scripts/core/src/output.sh"

##? Link Raycast scripts for .Sloth in your raycastr directory path
##?
##?
##? Usage:
##?   raycast [-h | --help]
##?   raycast [-v | --version]
##?
##? Options:
##?   -h --help     Show this help
##?   -v --version  Show the program version
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
#? v1.0.0
docs::parse "$@"

output::write "This can not be done automatically"
output::write "1. Open Raycast Preferences > Extensions"
output::write "2. Click on the \`+\` icon button and choose \`Add Script Directory\`"
output::write "3. Adds: \`${SLOTH_PATH:-}/_raycast\`"
output::empty_line
output::answer "🥳 🎉 Enjoy"
