#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
. "${SLOTH_PATH:-${DOTLY_PATH:-}}/scripts/core/src/_main.sh"
dot::load_library "dotly.sh"

# Default value
files=()

##? Static analysis of all sloth/dotly related bash files
##?
##? Usage:
##?    static_analysis [--dotfiles | -d]
##?    static_analysis [<files>...]
##?
##? Options:
##?    --help -h      Gives this help
##?    --dotfiles -d  Execute against your `DOTFILES_PATH`` instead of Sloth/Dotly core
##?
#? v2.1.0
if [[ "${1:-}" == "-h" || "${1:-}" = "--help" || "${1:-}" == "-v" || "${1:-}" == "--version" ]] || package::is_installed "docopts"; then
  docs::parse "$@"
elif [[ "${1:-}" = "--dotfiles" ]] || [[ "${1:-}" == "-d" ]]; then
  dotfiles=true
  shift

  if [[ $# -gt 0 ]]; then
    files=("$@")
  fi
fi
script::depends_on shellcheck

if [[ ${#files[@]} -gt 0 ]]; then
  printf "%s\n" "${files[@]}" | sort --unique | xargs shellcheck -s bash -S warning -e SC1090 -e SC2010 -e SC2154
elif ${dotfiles:-false}; then
  dotly::list_dotfiles_bash_files | sort --unique | xargs shellcheck -s bash -S warning -e SC1090 -e SC2010 -e SC2154
else
  dotly::list_bash_files | sort --unique | xargs shellcheck -s bash -S warning -e SC1090 -e SC2010 -e SC2154
fi
