#!/usr/bin/env bash

set -euo pipefail

[[ -z "${SLOTH_PATH:-}" ]] && exit 1

#shellcheck source=/dev/null
. "${SLOTH_PATH:-}/scripts/core/src/_main.sh"

##? Something went terribly wrong
##?
##?
##? Usage:
##?   wrong [-h | --help]
##?   wrong [-v | --version]
##?
##? Options:
##?   -h --help     Show this help
##?   -v --version  Show the program version
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
##?
#? v1.0.0

"${SLOTH_PATH:-}/bin/open" "https://www.youtube.com/watch?v=t3otBjVZzT0"
