#!/usr/bin/env bash
set -euo pipefail

#shellcheck disable=1091
. "${SLOTH_PATH:-}/scripts/core/src/_main.sh"
#shellcheck disable=SC2034
FORCED_PKGMGR="brew"

##? Some brew utils.
##?   - If cleanup does not receive any param will take your
##?     dumped Brewfile from dotly if exist. If does not exists
##?     and you don't provide a Brewfile will do nothing.
##?
##? Usage:
##?   brew list_installed
##?   brew cleanup [--prompt|-p|--never-prompt|-n] [<optional_path_brewfile>]
##?
##? Options:
##?   --prompt -p        You will be asked always for a file to restore in every package manager or lang
##?   --never-prompt -n  You will never be asked for any file to restore, if there is no file with the
##?                      same name as current hostname the package/lang is ignored and continue to try
##?                      with next package
##?
#? v2.0.0
docs::parse "$@"

if ! platform::command_exists brew; then
  output::error "Brew command does not exits"
  exit 4
fi

case "${1:-}" in
  "list_installed")
    brew leaves
    ;;
  "cleanup")
    BREW_PATH="${BREW_PATH:-$DOTFILES_PATH/os/$(platform::os)/brew}"
    HOMEBREW_DUMP_FILE_PATH="${optional_path_brewfile:-$(package::exists_dump_current_machine_file "$BREW_PATH")}"

    if ! ${never_prompt:-false}; then
      [[ -z "$HOMEBREW_DUMP_FILE_PATH" ]] || ${prompt:-false} && HOMEBREW_DUMP_FILE_PATH="$(package::which_file "$BREW_PATH" "Select Brewfile to import")"
    fi

    if [[ -f $HOMEBREW_DUMP_FILE_PATH ]]; then
      cleanup_cmd="$(which brew) bundle --file=\"${HOMEBREW_DUMP_FILE_PATH}\" --force cleanup"
      output::write "This will execute the command... "
      output::write "    $cleanup_cmd"

      if output::yesno "Still want to perform the action"; then
        $(which brew) bundle --file="${HOMEBREW_DUMP_FILE_PATH}" --force cleanup
        output::solution "Cleanup performed, your system only have the Brewfile packages"
      else
        output::error "User aborted"
        exit 1
      fi

      if output::yesno "Do you want to execute additional 'brew cleanup'"; then
        $(which brew) cleanup
      fi
    else
      output::error "No Brewfile found"
    fi
    ;;
  *)
    exit 1
    ;;
esac
