#!/usr/bin/env bash

set -euo pipefail

[[ -z "${SLOTH_PATH:-}" ]] && exit 1

#shellcheck disable=SC1091
. "${SLOTH_PATH:-}/scripts/core/_main.sh"

##? Install a package
##?
##? Usage:
##?    check [-v | --version]
##?    check [-h | --help]
##?    check <package_name>
##?
##? Options:
##?    -h --help      Show script help
##?    -v --version   Show script version
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
##?
#? v1.0.0
if ! ${DOTLY_INSTALLER:-false} && package::is_installed "docopts" || [[ "${1:-}" == "-h" || "${1:-}" == "--help" || "${1:-}" == "-v" || "${1:-}" == "--version" ]]; then
  docs::parse "$@"
else
  package_name="${1:-}"
  shift
fi

package_name="$(str::to_lower "$package_name")"

if [[ -z "${package_name:-}" ]]; then
  output::error "No package name provided"
  exit 1
fi

if package::is_installed "$package_name"; then
  log::success "$package_name already installed" && exit 0
fi

log::error "$package_name is not installed" && exit 1
