#!/usr/bin/env bash
#shellcheck disable=SC1091

set -euo pipefail

. "${SLOTH_PATH:-${DOTLY_PATH:-}}/scripts/core/src/_main.sh"

update_all_error() {
  [[ -n "${1:-}" ]] && output::write "Error updating ${1:-} apps. See \`dot self debug\` for view errors"
}

##? Update all packages
##?
##? Usage:
##?   update_all [--split] [<package_managers>...]
##?
##? Options:
##?   --split  Split terminal to show log and progress if tmux is installed or can be installed
##?
##? Arguments:
##?   package_manager  Package manager to use for updating (could be registry, cargo, apt, yum, etc.)
##?
#? v3.1.0

"${SLOTH_PATH:-${DOTLY_PATH:-}}/bin/up" "$@"
